### ISSUE TITLE
应用名字不支持中划线

### ISSUE THREAD

**Issue by Colstuwjx** [tal-tech/go-zero#353]
如题，发现应用名如果是 `xxx-xxx` 这样的话会报错：

```
# goctl api new kube-release
panic: route [/from/:name] handler [Kube-ReleaseHandler] invalid, handler name should only contains letter or digit

goroutine 1 [running]:
github.com/tal-tech/go-zero/tools/goctl/api/gogen.getHandlerName(...)
	/Users/jacky/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.1/tools/goctl/api/gogen/genhandlers.go:171
github.com/tal-tech/go-zero/tools/goctl/api/gogen.getRoutes(0xc000238120, 0xc000290760, 0xc00020e4b0, 0x1042dea, 0xc000039800, 0xc00020e4c0)
	/Users/jacky/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.1/tools/goctl/api/gogen/genroutes.go:187 +0xb8a
github.com/tal-tech/go-zero/tools/goctl/api/gogen.genRoutes(0xc0001a8120, 0x30, 0xc0002742e0, 0xc000238120, 0x0, 0x0)
	/Users/jacky/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.1/tools/goctl/api/gogen/genroutes.go:69 +0x7b
github.com/tal-tech/go-zero/tools/goctl/api/gogen.DoGenProject(0xc0001e2140, 0x41, 0xc0001a8120, 0x30, 0x161295d, 0x6, 0x0, 0x0)
	/Users/jacky/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.1/tools/goctl/api/gogen/gen.go:64 +0x2af
github.com/tal-tech/go-zero/tools/goctl/api/new.NewService(0xc00023e9a0, 0x0, 0x0)
	/Users/jacky/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.1/tools/goctl/api/new/newservice.go:64 +0x45f
github.com/urfave/cli.HandleAction(0x1566480, 0x16452b0, 0xc00023e9a0, 0xc00023e9a0, 0x0)
	/Users/jacky/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xfd
github.com/urfave/cli.Command.Run(0x160f748, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1623603, 0x17, 0x0, ...)
	/Users/jacky/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x58e
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001e4380, 0xc00023e6e0, 0x0, 0x0)
	/Users/jacky/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x954
github.com/urfave/cli.Command.startApp(0x160f679, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16253fd, 0x1a, 0x0, ...)
	/Users/jacky/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x87f
github.com/urfave/cli.Command.Run(0x160f679, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16253fd, 0x1a, 0x0, ...)
	/Users/jacky/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x9f4
github.com/urfave/cli.(*App).Run(0xc0001e41c0, 0xc0001b0000, 0x4, 0x4, 0x0, 0x0)
	/Users/jacky/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x7e8
main.main()
	/Users/jacky/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.1/tools/goctl/goctl.go:505 +0x18b
```

**Comment by kevwan** [comment]
只是api new这个子命令不支持中划线，因为需要被用来当做handler名字的一部分
