### ISSUE TITLE
StructHandle throw an Recover Error

### ISSUE THREAD

**Issue by YjLeo** [tal-tech/go-zero#419]
there was a moment when i set the map[string]map[string]interface{} in map[string]string Request Struct。
i get.
{"@timestamp":"2021-01-26T21:50:32.198+08","level":"error","content":"recoverhandler.go:15 (/outer/resource-space/bind - 127.0.0.1:54296) reflect.Value.SetMapIndex: value of type interface {} is not assignable to type string\n
goroutine 50 [running]:\nruntime/debug.Stack(0xc0002cccc8, 0x9323e0, 0xc0002882a0)\n\tC:/Users/Administrator/sdk/go1.14.7/src/runtime/debug/stack.go:24 +0xa4\ngithub.com/tal-tech/go-zero/rest/handler.RecoverHandler.func1.1(0xc
00029e300, 0xac4220, 0xc000280480)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/rest/handler/recoverhandler.go:15 +0x61\npanic(0x9323e0, 0xc0002882a0)\n\tC:/Users/Administrator/sdk/go1.14.7/src/runti
me/panic.go:969 +0x174\nreflect.Value.assignTo(0x9505e0, 0xc000288290, 0x94, 0xa073d6, 0x19, 0x9323e0, 0x0, 0x9323e0, 0xc000288280, 0x98)\n\tC:/Users/Administrator/sdk/go1.14.7/src/reflect/value.go:2411 +0x42d\nreflect.Value.S
etMapIndex(0x95d220, 0xc00028c510, 0x15, 0x9323e0, 0xc000288280, 0x98, 0x9505e0, 0xc000288290, 0x94)\n\tC:/Users/Administrator/sdk/go1.14.7/src/reflect/value.go:1674 +0x1e2\ngithub.com/tal-tech/go-zero/core/mapping.(*Unmarshal
er).generateMap(0xc000004620, 0xad09e0, 0x9323e0, 0xad09e0, 0x9323e0, 0x95cf80, 0xc00028c390, 0x4, 0x2030000, 0xc0002cd1b0, ...)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/core/mapping/unmarshaler.
go:589 +0x404\ngithub.com/tal-tech/go-zero/core/mapping.(*Unmarshaler).fillMap(0xc000004620, 0x8fef53, 0x6, 0x0, 0x0, 0xad09e0, 0x95d220, 0x8fef5b, 0xd, 0x38, ...)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-ze
ro@v1.1.2/core/mapping/unmarshaler.go:432 +0xe0\ngithub.com/tal-tech/go-zero/core/mapping.(*Unmarshaler).processFieldPrimitive(0xc000004620, 0x8fef53, 0x6, 0x0, 0x0, 0xad09e0, 0x95d220, 0x8fef5b, 0xd, 0x38, ...)\n\tC:/Users/Ad
ministrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/core/mapping/unmarshaler.go:237 +0x4ac\ngithub.com/tal-tech/go-zero/core/mapping.(*Unmarshaler).processFieldNotFromString(0xc000004620, 0x8fef53, 0x6, 0x0, 0x0, 0xad09e
0, 0x95d220, 0x8fef5b, 0xd, 0x38, ...)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/core/mapping/unmarshaler.go:211 +0x29c\ngithub.com/tal-tech/go-zero/core/mapping.(*Unmarshaler).processNamedFieldWi
thValue(0xc000004620, 0x8fef53, 0x6, 0x0, 0x0, 0xad09e0, 0x95d220, 0x8fef5b, 0xd, 0x38, ...)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/core/mapping/unmarshaler.go:362 +0x281\ngithub.com/tal-tech/g
o-zero/core/mapping.(*Unmarshaler).processNamedField(0xc000004620, 0x8fef53, 0x6, 0x0, 0x0, 0xad09e0, 0x95d220, 0x8fef5b, 0xd, 0x38, ...)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/core/mapping/unm
arshaler.go:341 +0x28f\ngithub.com/tal-tech/go-zero/core/mapping.(*Unmarshaler).processField(0xc000004620, 0x8fef53, 0x6, 0x0, 0x0, 0xad09e0, 0x95d220, 0x8fef5b, 0xd, 0x38, ...)\n\tC:/Users/Administrator/go/pkg/mod/github.com/
tal-tech/go-zero@v1.1.2/core/mapping/unmarshaler.go:188 +0x21c\ngithub.com/tal-tech/go-zero/core/mapping.(*Unmarshaler).unmarshalWithFullName(0xc000004620, 0xabb580, 0xc00028c360, 0x9223e0, 0xc000284140, 0x0, 0x0, 0xc0002b8000
, 0xc0002cd9d8)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/core/mapping/unmarshaler.go:96 +0x3a2\ngithub.com/tal-tech/go-zero/core/mapping.(*Unmarshaler).UnmarshalValuer(0xc000004620, 0xabb580, 0xc
00028c360, 0x9223e0, 0xc000284140, 0xc0002822a0, 0xc0002822c0)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/core/mapping/unmarshaler.go:74 +0x62\ngithub.com/tal-tech/go-zero/core/mapping.(*Unmarshale
r).Unmarshal(0xc000004620, 0xc00028c360, 0x9223e0, 0xc000284140, 0x0, 0x0)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/core/mapping/unmarshaler.go:70 +0x5c\ngithub.com/tal-tech/go-zero/core/mapping.
unmarshalJsonReader(0xabaa00, 0xc000282280, 0x9223e0, 0xc000284140, 0xc000004620, 0x0, 0x0)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/core/mapping/jsonunmarshaler.go:36 +0xbd\ngithub.com/tal-tech/
go-zero/core/mapping.UnmarshalJsonReader(...)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/core/mapping/jsonunmarshaler.go:18\ngithub.com/tal-tech/go-zero/rest/httpx.ParseJsonBody(0xc00029e300, 0x922
3e0, 0xc000284140, 0x0, 0x0)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/rest/httpx/requests.go:92 +0xe8\ngithub.com/tal-tech/go-zero/rest/httpx.Parse(0xc00029e300, 0x9223e0, 0xc000284140, 0x0, 0x0)
\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/rest/httpx/requests.go:36 +0xc4\nstorage-core/api/internal/handler.BindHandler.func1(0xac3d60, 0xc000282220, 0xc00029e300)\n\tF:/工作文档/golang项目源码/
storage-core/api/internal/handler/bindhandler.go:20 +0x7e\nnet/http.HandlerFunc.ServeHTTP(0xc00008eb20, 0xac3d60, 0xc000282220, 0xc00029e300)\n\tC:/Users/Administrator/sdk/go1.14.7/src/net/http/server.go:2041 +0x4b\ngithub.com
/tal-tech/go-zero/rest/handler.GunzipHandler.func1(0xac3d60, 0xc000282220, 0xc00029e300)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/rest/handler/gunziphandler.go:25 +0xc8\nnet/http.HandlerFunc.Serv
eHTTP(0xc000089340, 0xac3d60, 0xc000282220, 0xc00029e300)\n\tC:/Users/Administrator/sdk/go1.14.7/src/net/http/server.go:2041 +0x4b\ngithub.com/tal-tech/go-zero/rest/handler.MaxBytesHandler.func2.1(0xac3d60, 0xc000282220, 0xc00
029e300)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/rest/handler/maxbyteshandler.go:23 +0x14f\nnet/http.HandlerFunc.ServeHTTP(0xc000089360, 0xac3d60, 0xc000282220, 0xc00029e300)\n\tC:/Users/Adminis
trator/sdk/go1.14.7/src/net/http/server.go:2041 +0x4b\ngithub.com/tal-tech/go-zero/rest/handler.PromethousHandler.func1.1(0xac4220, 0xc000280480, 0xc00029e300)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v
1.1.2/rest/handler/prometheushandler.go:44 +0x130\nnet/http.HandlerFunc.ServeHTTP(0xc0000ea4b0, 0xac4220, 0xc000280480, 0xc00029e300)\n\tC:/Users/Administrator/sdk/go1.14.7/src/net/http/server.go:2041 +0x4b\ngithub.com/tal-tec
h/go-zero/rest/handler.MetricHandler.func1.1(0xac4220, 0xc000280480, 0xc00029e300)\n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/rest/handler/metrichandler.go:20 +0xd0\nnet/http.HandlerFunc.ServeHTTP(
0xc000089380, 0xac4220, 0xc000280480, 0xc00029e300)\n\tC:/Users/Administrator/sdk/go1.14.7/src/net/http/server.go:2041 +0x4b\ngithub.com/tal-tech/go-zero/rest/handler.RecoverHandler.func1(0xac4220, 0xc000280480, 0xc00029e300)\
n\tC:/Users/Administrator/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.2/rest/handler/recoverhandler.go:20 +0x8a\nnet/http.HandlerFunc.ServeHTTP(0xc0000893a0, 0xac4220, 0xc000280480, 0xc00029e300)\n\tC:/Users/Administrator/sdk/
go1.14.7/src/net/http/server.go:2041 +0x4b\nnet/http.(*timeoutHandler).ServeHTTP.func1(0xc0002804e0, 0xc0000b8240, 0xc000280480, 0xc00029e300, 0xc0002aa0c0)\n\tC:/Users/Administrator/sdk/go1.14.7/src/net/http/server.go:3267 +0
x86\ncreated by net/http.(*timeoutHandler).ServeHTTP\n\tC:/Users/Administrator/sdk/go1.14.7/src/net/http/server.go:3261 +0x22d\n"}

the leak:

![image](https://user-images.githubusercontent.com/23043492/105852565-9c738080-601f-11eb-84c6-cbf67bfc1b18.png)

**Comment by YjLeo** [comment]
fix#420

**Comment by YjLeo** [comment]
fix #420

**Comment by YjLeo** [comment]
New unit test. If exception is not caught, return panic. Normally, return error
#514
